#!/bin/bash
#
# lint-commit-range.sh - Validate every non-merge commit subject in a range
# against the project's Conventional Commits format.
#
# The format rules themselves live in check-commit-subject.sh, which this
# script calls once per subject. This script owns only the iteration: which
# commits are in scope, how results are reported, and what a failure prints.
#
# Called by .github/workflows/commit-lint.yml. Kept as a script rather than
# inline YAML per conventions/workflow-scripts.md — the range semantics and
# the empty-range case are worth being able to exercise without pushing a
# commit.
#
# Usage:
#   ./scripts/lint-commit-range.sh <base-ref> <head-ref>
#   ./scripts/lint-commit-range.sh --stdin      # subjects on stdin, one per line
#
# Exits 0 if every subject is valid, 1 otherwise.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHECK="$SCRIPT_DIR/check-commit-subject.sh"

usage() {
  cat >&2 <<EOF
usage: $0 <base-ref> <head-ref>
       $0 --stdin
EOF
  exit 2
}

subjects=()

if [ "${1:-}" = "--stdin" ]; then
  while IFS= read -r line; do
    [ -n "$line" ] || continue
    subjects+=("$line")
  done
elif [ "$#" -eq 2 ]; then
  # --no-merges: a merge commit's subject is generated by git, not authored,
  # so holding it to the format would fail PRs for something no one typed.
  while IFS= read -r line; do
    subjects+=("$line")
  done < <(git log --no-merges --format='%s' "$1..$2")
else
  usage
fi

if [ "${#subjects[@]}" -eq 0 ]; then
  echo "No non-merge commits to lint."
  exit 0
fi

err_file="$(mktemp)"
trap 'rm -f "$err_file"' EXIT

fail=0
for subject in "${subjects[@]}"; do
  echo "→ $subject"
  if "$CHECK" "$subject" 2>"$err_file"; then
    echo "   ✓ ok"
  else
    fail=1
    sed 's/^/   /' "$err_file"
  fi
done

if [ "$fail" -ne 0 ]; then
  cat <<'EOF'

────────────────────────────────────────────────────────────────────
To fix: rebase and reword the offending commits, then force-push:
  git rebase -i <base-sha>
  # change `pick` → `reword`, save, edit subjects
  git push --force-with-lease

Local enforcement is also wired up via .githooks/commit-msg — run
`git config core.hooksPath .githooks` once per clone to enable it.
────────────────────────────────────────────────────────────────────
EOF
  exit 1
fi
