#!/bin/bash
#
# test-check-locales.sh - Exercise scripts/check-locales.sh.
#
#   ./scripts/test-check-locales.sh
#
# The real repository is checked directly for the cases that must hold on main.
# Everything else runs against a fixture tree, because the failures worth
# testing -- a locale present in three registries out of four -- cannot be
# staged in the checked-in files without breaking the build.
#
# Fixtures are written by printf rather than edited by sed: BSD sed does not
# interpret \t, and project.pbxproj is tab-indented, so a sed-built fixture
# silently fails to match and the test passes for the wrong reason.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHECK="$SCRIPT_DIR/check-locales.sh"

pass=0
fail=0
ok()  { pass=$((pass + 1)); printf '  ok    %s\n' "$1"; }
bad() { fail=$((fail + 1)); printf '  FAIL  %s\n        %s\n' "$1" "$2"; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

METADATA_FILES="description keywords name promotional_text release_notes subtitle marketing_url privacy_url support_url"

write_manifest() {
  local root="$1"; shift
  printf '%s\n' "$@" > "$root/.locales"
}

write_pbxproj() {
  local root="$1"; shift
  local region
  {
    printf '\t\t\tknownRegions = (\n'
    for region in "$@"; do printf '\t\t\t\t%s,\n' "$region"; done
    printf '\t\t\t);\n'
  } > "$root/LeavesOfBlocks.xcodeproj/project.pbxproj"
}

# Entries are "key:lang,lang" or "key:fragment" -- the latter being the shape
# Xcode gives an auto-extracted format fragment: a comment and no localizations.
write_catalog() {
  local root="$1"; shift
  local entry key langs lang first=1 firstlang
  {
    printf '{\n  "sourceLanguage" : "en",\n  "strings" : {\n'
    for entry in "$@"; do
      key="${entry%%:*}"
      langs="${entry#*:}"
      [ "$first" -eq 1 ] || printf ',\n'
      first=0
      printf '    "%s" : {\n' "$key"
      if [ "$langs" = "fragment" ]; then
        printf '      "comment" : "Auto-generated.",\n      "isCommentAutoGenerated" : true\n'
      else
        printf '      "localizations" : {\n'
        firstlang=1
        for lang in ${langs//,/ }; do
          [ "$firstlang" -eq 1 ] || printf ',\n'
          firstlang=0
          printf '        "%s" : { "stringUnit" : { "state" : "translated", "value" : "%s text" } }' "$lang" "$lang"
        done
        printf '\n      }\n'
      fi
      printf '    }'
    done
    printf '\n  },\n  "version" : "1.1"\n}\n'
  } > "$root/LeavesOfBlocks/Resources/Localizable.xcstrings"
}

write_constants() {
  local root="$1"; shift
  local locale first=1
  {
    printf 'SCREENSHOT_LANGUAGES = [\n'
    for locale in "$@"; do
      [ "$first" -eq 1 ] || printf ',\n'
      first=0
      printf '  "%s"' "$locale"
    done
    printf '\n]\n'
  } > "$root/fastlane/Constants.rb"
}

write_metadata() {
  local root="$1" locale="$2" file
  mkdir -p "$root/fastlane/metadata/$locale"
  for file in $METADATA_FILES; do
    printf 'placeholder\n' > "$root/fastlane/metadata/$locale/$file.txt"
  done
}

# A consistent repository: one store locale, one app language, one real key and
# one format fragment. Each test breaks exactly one thing afterwards.
make_fixture() {
  local root="$1"
  rm -rf "$root"
  mkdir -p "$root/LeavesOfBlocks.xcodeproj" "$root/LeavesOfBlocks/Resources" \
           "$root/LeavesOfBlocks/Views" "$root/fastlane/metadata"
  write_manifest "$root" "en-US	en"
  write_pbxproj "$root" en Base
  write_catalog "$root" "game_over:en" "•:fragment"
  write_constants "$root" en-US
  write_metadata "$root" en-US
  printf 'Text("game_over".localized)\n' > "$root/LeavesOfBlocks/Views/SomeView.swift"
}

# Combined output; returns the exit code.
run_fixture() { LOCALES_ROOT="$1" "$CHECK" 2>&1; }
# Problems only. Assertions that something is *not* demanded must read stderr:
# the success lines on stdout name every registry, so an absence assertion
# against combined output would be unfalsifiable.
# shellcheck disable=SC2069 # deliberate: "2>&1 >/dev/null" is stderr-only
fixture_err() { LOCALES_ROOT="$1" "$CHECK" 2>&1 >/dev/null; }
# The reported problems alone. The closing help block on stderr names all four
# registries, so an absence assertion has to read the "x" lines or it matches
# the help text and fails for a reason that has nothing to do with the check.
fixture_problems() { fixture_err "$1" | grep -F '✗' || true; }

echo "against the real repository"

"$CHECK" >/dev/null 2>&1; code=$?
if [ "$code" -eq 0 ]; then ok "the checked-in registries agree"; else bad "registries agree" "exit $code: $("$CHECK" 2>&1 >/dev/null | head -3)"; fi

out=$("$CHECK" --store 2>&1)
if [ "$out" = "en-US" ]; then ok "--store prints the declared store locales"; else bad "--store output" "got: $out"; fi

out=$("$CHECK" --app 2>&1 | tr '\n' ' ')
if [ "$out" = "en es " ]; then ok "--app prints the declared app languages"; else bad "--app output" "got: $out"; fi

echo
echo "argument handling"

"$CHECK" --bogus >/dev/null 2>&1; code=$?
if [ "$code" -eq 2 ]; then ok "an unknown flag is a usage error"; else bad "unknown flag exits 2" "got $code"; fi

echo
echo "the manifest itself"

make_fixture "$TMP/base"
run_fixture "$TMP/base" >/dev/null 2>&1; code=$?
if [ "$code" -eq 0 ]; then ok "a consistent fixture passes"; else bad "consistent fixture passes" "exit $code: $(fixture_err "$TMP/base" | head -3)"; fi

make_fixture "$TMP/nomanifest"; rm "$TMP/nomanifest/.locales"
run_fixture "$TMP/nomanifest" >/dev/null 2>&1; code=$?
if [ "$code" -eq 2 ]; then ok "a missing manifest is a setup error"; else bad "missing manifest exits 2" "got $code"; fi

make_fixture "$TMP/emptymanifest"; write_manifest "$TMP/emptymanifest" "# only a comment"
run_fixture "$TMP/emptymanifest" >/dev/null 2>&1; code=$?
if [ "$code" -eq 2 ]; then ok "a manifest declaring nothing is a setup error"; else bad "empty manifest exits 2" "got $code"; fi

make_fixture "$TMP/badcols"; write_manifest "$TMP/badcols" "en-US	en	extra"
run_fixture "$TMP/badcols" >/dev/null 2>&1; code=$?
if [ "$code" -eq 2 ]; then ok "a malformed manifest row is a setup error"; else bad "malformed row exits 2" "got $code"; fi

make_fixture "$TMP/onecol"; write_manifest "$TMP/onecol" "en-US"
run_fixture "$TMP/onecol" >/dev/null 2>&1; code=$?
if [ "$code" -eq 2 ]; then ok "a row missing the second column is a setup error"; else bad "one-column row exits 2" "got $code"; fi

make_fixture "$TMP/bothdashes"; write_manifest "$TMP/bothdashes" "en-US	en" "-	-"
run_fixture "$TMP/bothdashes" >/dev/null 2>&1; code=$?
if [ "$code" -eq 2 ]; then ok "a row shipping on neither side is a setup error"; else bad "empty row exits 2" "got $code"; fi

make_fixture "$TMP/comments"; write_manifest "$TMP/comments" "# store	app" "" "en-US	en"
run_fixture "$TMP/comments" >/dev/null 2>&1; code=$?
if [ "$code" -eq 0 ]; then ok "comments and blank lines are ignored"; else bad "comments ignored" "exit $code: $(fixture_err "$TMP/comments" | head -2)"; fi

echo
echo "the two identifier spaces are checked independently"

# The state Spanish is in today: shipped in-app, no App Store listing yet. The
# store column is "-", so the metadata and screenshot checks skip it while
# knownRegions and the catalog are still held to it.
make_fixture "$TMP/inapp"; write_manifest "$TMP/inapp" "en-US	en" "-	es"
run_fixture "$TMP/inapp" >/dev/null 2>&1; code=$?
if [ "$code" -eq 1 ]; then ok "an in-app-only language is still checked app-side"; else bad "in-app-only checked app-side" "want exit 1, got $code"; fi

err=$(fixture_problems "$TMP/inapp")
if grep -qF "metadata" <<<"$err"; then
  bad "in-app-only skips the store side" "metadata was demanded: $(grep -F metadata <<<"$err" | head -1)"
else
  ok "an in-app-only language demands no metadata directory"
fi

make_fixture "$TMP/inapp2"; write_manifest "$TMP/inapp2" "en-US	en" "-	es"
write_pbxproj "$TMP/inapp2" en es Base
write_catalog "$TMP/inapp2" "game_over:en,es" "•:fragment"
run_fixture "$TMP/inapp2" >/dev/null 2>&1; code=$?
if [ "$code" -eq 0 ]; then ok "an in-app-only language passes once both app registries carry it"; else bad "in-app-only passes" "exit $code: $(fixture_err "$TMP/inapp2" | head -3)"; fi

# The mirror image: a store locale with no in-app language, which is what a
# localized listing shipped ahead of a translated build looks like.
make_fixture "$TMP/storeonly"; write_manifest "$TMP/storeonly" "en-US	en" "de-DE	-"
run_fixture "$TMP/storeonly" >/dev/null 2>&1; code=$?
if [ "$code" -eq 1 ]; then ok "a store-only locale is still checked store-side"; else bad "store-only checked store-side" "want exit 1, got $code"; fi

err=$(fixture_problems "$TMP/storeonly")
if grep -qE "knownRegions|xcstrings" <<<"$err"; then
  bad "store-only skips the app side" "an app registry was held to it: $(head -1 <<<"$err")"
else
  ok "a store-only locale demands no knownRegions or catalog entry"
fi

make_fixture "$TMP/storeonly2"; write_manifest "$TMP/storeonly2" "en-US	en" "de-DE	-"
write_constants "$TMP/storeonly2" en-US de-DE
write_metadata "$TMP/storeonly2" de-DE
run_fixture "$TMP/storeonly2" >/dev/null 2>&1; code=$?
if [ "$code" -eq 0 ]; then ok "a store-only locale passes once the listing exists"; else bad "store-only passes" "exit $code: $(fixture_err "$TMP/storeonly2" | head -3)"; fi

echo
echo "knownRegions"

make_fixture "$TMP/regions"; write_manifest "$TMP/regions" "en-US	en" "es-ES	es"
write_constants "$TMP/regions" en-US es-ES
write_metadata "$TMP/regions" es-ES
write_catalog "$TMP/regions" "game_over:en,es" "•:fragment"
run_fixture "$TMP/regions" >/dev/null 2>&1; code=$?
if [ "$code" -eq 1 ]; then ok "a language missing from knownRegions fails"; else bad "missing knownRegions entry fails" "want exit 1, got $code"; fi

err=$(fixture_err "$TMP/regions")
if grep -qF "knownRegions" <<<"$err"; then ok "the failing registry is named"; else bad "registry named" "got: $err"; fi

make_fixture "$TMP/extraregion"; write_pbxproj "$TMP/extraregion" en fr Base
run_fixture "$TMP/extraregion" >/dev/null 2>&1; code=$?
if [ "$code" -eq 1 ]; then ok "an undeclared region in knownRegions fails"; else bad "undeclared region fails" "want exit 1, got $code"; fi

make_fixture "$TMP/base_region_ok"
err=$(fixture_problems "$TMP/base_region_ok")
if grep -qF "Base" <<<"$err"; then bad "Base is allowed" "Base was reported: $err"; else ok "the Base pseudo-region is not an undeclared language"; fi

make_fixture "$TMP/noregions"
printf 'nothing here\n' > "$TMP/noregions/LeavesOfBlocks.xcodeproj/project.pbxproj"
run_fixture "$TMP/noregions" >/dev/null 2>&1; code=$?
if [ "$code" -eq 2 ]; then ok "an unreadable knownRegions block is a setup error"; else bad "unreadable knownRegions exits 2" "got $code"; fi

echo
echo "the string catalog"

make_fixture "$TMP/catalog"; write_manifest "$TMP/catalog" "en-US	en" "es-ES	es"
write_pbxproj "$TMP/catalog" en es Base
write_constants "$TMP/catalog" en-US es-ES
write_metadata "$TMP/catalog" es-ES
run_fixture "$TMP/catalog" >/dev/null 2>&1; code=$?
if [ "$code" -eq 1 ]; then ok "a language absent from the catalog fails"; else bad "absent catalog language fails" "want exit 1, got $code"; fi

err=$(fixture_err "$TMP/catalog")
if grep -qF "Localizable.xcstrings" <<<"$err"; then ok "the catalog is named"; else bad "catalog named" "got: $err"; fi

make_fixture "$TMP/undeclared_lang"; write_catalog "$TMP/undeclared_lang" "game_over:en,fr" "•:fragment"
run_fixture "$TMP/undeclared_lang" >/dev/null 2>&1; code=$?
if [ "$code" -eq 1 ]; then ok "an undeclared language in the catalog fails"; else bad "undeclared catalog language fails" "want exit 1, got $code"; fi

# A key containing "." cannot be addressed as a plutil keypath, so its
# languages come back empty -- indistinguishable from a format fragment, and
# missing from every coverage figure without a word about it.
make_fixture "$TMP/dotkey"; write_catalog "$TMP/dotkey" "game_over:en" "some.key:en"
run_fixture "$TMP/dotkey" >/dev/null 2>&1; code=$?
if [ "$code" -eq 2 ]; then ok "a key plutil cannot address is a setup error"; else bad "dotted key exits 2" "got $code"; fi

make_fixture "$TMP/nocatalog"; rm "$TMP/nocatalog/LeavesOfBlocks/Resources/Localizable.xcstrings"
run_fixture "$TMP/nocatalog" >/dev/null 2>&1; code=$?
if [ "$code" -eq 2 ]; then ok "a missing catalog is a setup error"; else bad "missing catalog exits 2" "got $code"; fi

echo
echo "partial translation is reported, not failed"

# Coverage is information, not a gate: #114 finishes Spanish, and this check has
# to be able to land before it does.
make_fixture "$TMP/partial"; write_manifest "$TMP/partial" "en-US	en" "-	es"
write_pbxproj "$TMP/partial" en es Base
write_catalog "$TMP/partial" "game_over:en,es" "only_english:en" "•:fragment"
run_fixture "$TMP/partial" >/dev/null 2>&1; code=$?
if [ "$code" -eq 0 ]; then ok "an incomplete translation does not fail the check"; else bad "incomplete translation passes" "exit $code: $(fixture_err "$TMP/partial" | head -3)"; fi

out=$(run_fixture "$TMP/partial")
if grep -qE '^ +es: 1 of 2 translated' <<<"$out"; then
  ok "the untranslated count is reported"
else
  bad "coverage reported" "want 'es: 1 of 2 translated', got: $(grep -iE 'es|coverage' <<<"$out" | tail -3)"
fi

# The format fragments ("%@", the bullet) carry no localizations at all and are
# Xcode's to manage. Counted as untranslated, full coverage would be
# unreachable and the report would be noise -- so the denominator is 2, not 3.
if grep -qE '^ +en: 2 of 2 translated' <<<"$out"; then
  ok "source-only format fragments are excluded from coverage"
else
  bad "fragments excluded" "want 'en: 2 of 2 translated', got: $(grep -iE 'en:' <<<"$out" | tail -2)"
fi

echo
echo "SCREENSHOT_LANGUAGES"

make_fixture "$TMP/screens"; write_constants "$TMP/screens" en-US de-DE
run_fixture "$TMP/screens" >/dev/null 2>&1; code=$?
if [ "$code" -eq 1 ]; then ok "an undeclared screenshot language fails"; else bad "undeclared screenshot language fails" "want exit 1, got $code"; fi

make_fixture "$TMP/screens2"; write_manifest "$TMP/screens2" "en-US	en" "es-ES	es"
write_pbxproj "$TMP/screens2" en es Base
write_catalog "$TMP/screens2" "game_over:en,es" "•:fragment"
write_metadata "$TMP/screens2" es-ES
run_fixture "$TMP/screens2" >/dev/null 2>&1; code=$?
if [ "$code" -eq 1 ]; then ok "a declared locale missing from SCREENSHOT_LANGUAGES fails"; else bad "missing screenshot language fails" "want exit 1, got $code"; fi

err=$(fixture_err "$TMP/screens2")
if grep -qF "SCREENSHOT_LANGUAGES" <<<"$err"; then ok "the constant is named"; else bad "constant named" "got: $err"; fi

make_fixture "$TMP/noconst"; rm "$TMP/noconst/fastlane/Constants.rb"
run_fixture "$TMP/noconst" >/dev/null 2>&1; code=$?
if [ "$code" -eq 2 ]; then ok "a missing Constants.rb is a setup error"; else bad "missing Constants.rb exits 2" "got $code"; fi

make_fixture "$TMP/noconstant"; printf 'OTHER = 1\n' > "$TMP/noconstant/fastlane/Constants.rb"
run_fixture "$TMP/noconstant" >/dev/null 2>&1; code=$?
if [ "$code" -eq 2 ]; then ok "a Constants.rb without the constant is a setup error"; else bad "absent constant exits 2" "got $code"; fi

echo
echo "App Store metadata"

make_fixture "$TMP/nometa"; rm -rf "$TMP/nometa/fastlane/metadata/en-US"
run_fixture "$TMP/nometa" >/dev/null 2>&1; code=$?
if [ "$code" -eq 1 ]; then ok "a missing metadata directory fails"; else bad "missing metadata dir fails" "want exit 1, got $code"; fi

make_fixture "$TMP/missingfile"; rm "$TMP/missingfile/fastlane/metadata/en-US/subtitle.txt"
run_fixture "$TMP/missingfile" >/dev/null 2>&1; code=$?
if [ "$code" -eq 1 ]; then ok "a missing metadata file fails"; else bad "missing metadata file fails" "want exit 1, got $code"; fi

err=$(fixture_err "$TMP/missingfile")
if grep -qF "subtitle.txt" <<<"$err"; then ok "the missing file is named"; else bad "missing file named" "got: $err"; fi

# An empty file is worse than a missing one: deliver uploads it and blanks the
# field on the live listing.
make_fixture "$TMP/emptyfile"; : > "$TMP/emptyfile/fastlane/metadata/en-US/description.txt"
run_fixture "$TMP/emptyfile" >/dev/null 2>&1; code=$?
if [ "$code" -eq 1 ]; then ok "an empty metadata file fails"; else bad "empty metadata file fails" "want exit 1, got $code"; fi

# The URL files are copied rather than translated, but a locale without them
# ships a listing with no support or privacy link.
make_fixture "$TMP/nourl"; rm "$TMP/nourl/fastlane/metadata/en-US/privacy_url.txt"
run_fixture "$TMP/nourl" >/dev/null 2>&1; code=$?
if [ "$code" -eq 1 ]; then ok "a missing URL file fails too"; else bad "missing URL file fails" "want exit 1, got $code"; fi

# A leftover directory from a dropped locale keeps being uploaded.
make_fixture "$TMP/straydir"; mkdir -p "$TMP/straydir/fastlane/metadata/fr-FR"
run_fixture "$TMP/straydir" >/dev/null 2>&1; code=$?
if [ "$code" -eq 1 ]; then ok "an undeclared metadata directory fails"; else bad "undeclared metadata dir fails" "want exit 1, got $code"; fi

# The loose files beside the locale directories (copyright.txt, the category
# files, app_rating_config.json) are listing-wide, not per-locale.
make_fixture "$TMP/loose"; printf 'Tim Veil\n' > "$TMP/loose/fastlane/metadata/copyright.txt"
run_fixture "$TMP/loose" >/dev/null 2>&1; code=$?
if [ "$code" -eq 0 ]; then ok "listing-wide metadata files are not mistaken for locales"; else bad "loose files ignored" "exit $code: $(fixture_err "$TMP/loose" | head -2)"; fi

echo
echo "every .localized key resolves"

make_fixture "$TMP/badkey"
printf 'Text("no_such_key".localized)\n' > "$TMP/badkey/LeavesOfBlocks/Views/Bad.swift"
run_fixture "$TMP/badkey" >/dev/null 2>&1; code=$?
if [ "$code" -eq 1 ]; then ok "a key with no catalog entry fails"; else bad "unresolved key fails" "want exit 1, got $code"; fi

err=$(fixture_err "$TMP/badkey")
if grep -qF "no_such_key" <<<"$err" && grep -qF "Bad.swift" <<<"$err"; then
  ok "the key and its file are named"
else
  bad "key and file named" "got: $err"
fi

# String+Extensions.swift documents the lookup with `"Game Over".localized`.
# That is an illustration, not a key, and no catalog entry backs it.
make_fixture "$TMP/comment"
printf '/// let title = "documented_example".localized\n' > "$TMP/comment/LeavesOfBlocks/Views/Doc.swift"
run_fixture "$TMP/comment" >/dev/null 2>&1; code=$?
if [ "$code" -eq 0 ]; then ok "a lookup inside a comment is not a key"; else bad "comment lookups ignored" "exit $code: $(fixture_err "$TMP/comment" | head -2)"; fi

# A block comment opens with "/*" -- only its continuation lines start with
# "*", so matching those alone leaves the first line of every /* ... */ block
# being read as live code.
make_fixture "$TMP/blockcomment"
printf '/* let title = "documented_example".localized */\n' > "$TMP/blockcomment/LeavesOfBlocks/Views/Block.swift"
run_fixture "$TMP/blockcomment" >/dev/null 2>&1; code=$?
if [ "$code" -eq 0 ]; then ok "a lookup on a block comment's opening line is not a key"; else bad "block comment opening ignored" "exit $code: $(fixture_problems "$TMP/blockcomment" | head -1)"; fi

# The continuation lines of the same block.
make_fixture "$TMP/blockbody"
printf '/*\n * let title = "documented_example".localized\n */\n' > "$TMP/blockbody/LeavesOfBlocks/Views/Body.swift"
run_fixture "$TMP/blockbody" >/dev/null 2>&1; code=$?
if [ "$code" -eq 0 ]; then ok "a lookup on a block comment's body line is not a key"; else bad "block comment body ignored" "exit $code: $(fixture_problems "$TMP/blockbody" | head -1)"; fi

make_fixture "$TMP/withargs"
printf 'Text("no_such_format".localized(with: 1))\n' > "$TMP/withargs/LeavesOfBlocks/Views/Args.swift"
run_fixture "$TMP/withargs" >/dev/null 2>&1; code=$?
if [ "$code" -eq 1 ]; then ok "localized(with:) lookups are checked too"; else bad "localized(with:) checked" "want exit 1, got $code"; fi

# Keys reached through .localizedGrade are mapped, not literal, and the
# fragments are keyed by punctuation -- neither may trip the literal scan.
make_fixture "$TMP/fragmentkey"
printf 'Text("•".localized)\n' > "$TMP/fragmentkey/LeavesOfBlocks/Views/Bullet.swift"
run_fixture "$TMP/fragmentkey" >/dev/null 2>&1; code=$?
if [ "$code" -eq 0 ]; then ok "a source-only fragment key still resolves"; else bad "fragment key resolves" "exit $code: $(fixture_err "$TMP/fragmentkey" | head -2)"; fi

echo
if [ "$fail" -eq 0 ]; then echo "All $pass checks passed."; exit 0; fi
echo "$fail failed, $pass passed."
exit 1
