name: iOS Build and Test

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.swift'
      - '**.xcodeproj/**'
      - '**.xcworkspace/**'
      - '**.xcdatamodeld/**'
      - '**.xcassets/**'
      - '**.storyboard'
      - '**.xib'
      - '**.plist'
      - '**.entitlements'
      - 'LeavesOfBlocks/**'
      - 'LeavesOfBlocksTests/**'
      - 'LeavesOfBlocksUITests/**'
      - '.github/workflows/ios.yml'
      - 'scripts/build.sh'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.swift'
      - '**.xcodeproj/**'
      - '**.xcworkspace/**'
      - '**.xcdatamodeld/**'
      - '**.xcassets/**'
      - '**.storyboard'
      - '**.xib'
      - '**.plist'
      - '**.entitlements'
      - 'LeavesOfBlocks/**'
      - 'LeavesOfBlocksTests/**'
      - 'LeavesOfBlocksUITests/**'
      - '.github/workflows/ios.yml'
      - 'scripts/build.sh'

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Environment
        run: ./scripts/build.sh info

      - name: Build
        run: ./scripts/build.sh build

      - name: Test
        run: ./scripts/build.sh test
